data class Post(
    var id: ULong = 0U,
    val ownerId: UInt = 0U,
    val fromId: UInt,
    val createdBy: UInt = 0U,
    val date: UInt = 0U,
    val text: String,
    val replyOwnerId: UInt = 0U,
    val replyPostId: UInt = 0U,
    val friendsOnly: Boolean = false,
    val comments: UInt = 0U,
    val copyright: UInt = 0U,
    val likes: UInt = 0U,
    val reposts: UInt = 0U,
    val views: UInt = 0U,
    val postType: PostTypes = PostTypes.post,
    val signerId: UInt = 0U,
    val canPin: Boolean = true,
    val canDelete: Boolean = true,
    val canEdit: Boolean = true,
    val isPinned: Boolean = false,
    val markedAsAds: Boolean = false,
    val isFavorite: Boolean = false,
    val donut: Boolean = false,
    val postponedId: UInt = 0U
)
